ARG BASE_IMAGE
FROM $BASE_IMAGE

RUN --mount=type=cache,target=/var/cache/apt \
  apt-get update -y || true && \
  apt-get install -y \
  ros-humble-isaac-ros-test \
  ros-humble-isaac-ros-argus-camera \
  ros-humble-isaac-ros-image-pipeline \
  ros-humble-isaac-ros-h264-encoder ros-humble-isaac-ros-h264-decoder \
  ros-humble-isaac-ros-yolov8 ros-humble-isaac-ros-tensor-rt ros-humble-isaac-ros-dnn-image-encoder \
  ros-humble-foxglove-bridge

# NOTES:
# ros-humble-isaac-ros-test is for building packages